- hosts: local
  connection: local
  vars:
    vdc: ecf25ac6-8500-445c-91f6-ad955f73f3a4
    vim_zone: myVzId
    vendor: Ericsson
    version: "1.0"

  tasks:

    - name: Deploy vapp (HOT package based. 1 VM connected to a network)
      ecm_vapp:
        name: "vapp1"
        vnfd_id: f41531d4-cb80-4578-8665-268a69f188ea
        vdc:  "{{vdc}}"
        vim_zone: "myVzId"
        description: "vapp deployed via custom ECM ansible module"
        vendor: "Ericsson"
        version: "1.0"
        parameters: {
            image_id_core: 6f326ccc-4c30-41ce-b742-c42e27fe3d03,
            ip_addr: 30.30.0.30,
            network_id: pattabi_network_1,
            subnet_id: pattabi_subnet_1
        }
        state: active
      register: vapp1

    - debug: var=vapp1

    - name: Create VAPP Connection Point (CP to the VAPP created in the previous step)
      ecm_cp:
        name: "vapp1_cp1"
        type: OAM
        description: "VAPP Connection Point"
        address: "1.1.1.1"
        address_type: subnet
        vapp_id: "{{ vapp1.id }}"
        state: active
      register: vapp1_cp1

    - debug: var=vapp1_cp1

    - name: Create Service (with the VAPP created in the previous step and 1 Service CP)
      ecm_service:
        name: "service1"
        type: "Simple Demo Service"
        description: "Demo Service"
        vendor: Ericsson
        version: 1.0
        vdc:  "{{vdc}}"
        vapps: [ "{{ vapp1.id }}" ]
        cps: [
          {
              "name": "service1_cp1",
              "type": "OAM",
              "description": "service connection point",
              "address": "2.2.2.2",
              "addressType": "subnet"
          }
        ]
        state: active
      register: service1

    - debug: var=service1

    - name: Create Service Connection Point (Adding another CP to the service created in the previous step)
      ecm_cp:
        name: "service1_cp2"
        type: OAM
        description: "VAPP Connection Point"
        address: "1.1.1.1"
        address_type: subnet
        service_id: "{{ service1.id }}"
        state: active
      register: service1_cp2

    - debug: var=service1_cp2


    - name: Create Virtual Link (1 VAPP CP and 1 Service CP)
      ecm_vlink:
        name: "service1_vlink1"
        type: Layer3
        description: "virtual link"
        vendor: Ericsson
        version: 1.0
        service_id: "{{ service1.id }}"
        cps: [
          "{{ vapp1_cp1.id }}",
          "{{ service1_cp2.id }}"
        ]
        provider_vl_id: demo
        state: active
      register: service1_vlink1

    - debug: var=service1_vlink1

    - pause:
          seconds: 3600
          prompt: "About to clean up the configuration ..."

    - name: Delete Virtual Link
      ecm_vlink:
        id: "{{service1_vlink1.id}}"
        state: deleted
      register: result
      tags:
        - vlink

    - debug: var=result

    - name: Delete Service
      ecm_service:
        id: "{{service1.id}}"
        state: deleted
      register: result
      tags:
        - service

    - debug: var=result

    - name: Delete vapp
      ecm_vapp:
        id: "{{vapp1.id}}"
        state: deleted
      register: result
      tags:
        - vapp

    - debug: var=result
